language: python
dist: bionic
sudo: required
python:
  - "3.6"
virtualenv:
  system_site_packages: true

install:
 - pip install -r requirements.txt
 - pip install coverage

script:
 - coverage report -m main.py

after_success:
 - pip install fandogh_cli
 - COLLECT_ERROR=True fandogh login --username $FAN_USR --password $FAN_PASS
 - fandogh image init --name=siahpoosh
 - fandogh image publish --version v$TRAVIS_JOB_NUMBER
 - fandogh service apply -f manifest.yaml -p token=$TOKEN
 - fandogh service deploy --version v$TRAVIS_JOB_NUMBER --name siahpoosh
